server:
  port: 8080

spring:
  thymeleaf:
    cache: false

  application:
    name: client # CHANGE THIS TO YOUR NAME

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/